name: Publish Python Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI (only on Ubuntu and Python 3.10)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        uses: pypa/gh-action-pypi-publish@v2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Test installation (optional)
        run: |
          pip install dist/*.whl
          python -c "import bigo"

